### PR TITLE
fix the bug

### PR DESCRIPTION
**Pull request by WeiYan-Lynn**
fix the bug of using hnsw algorithm to justify the failure of filtering when the documents that meet the requirements have low scores

### CODE REVIEW

**Review by zcdb — COMMENTED** [review]
Thank you for your suggestion. But lowerbound will update at line 340, is that enough?

**Comment by WeiYan-Lynn** [comment]
Obviously not, you can read the comments. And if there is no modification in your top, the lower limit will not be updated, resulting in an error exit from the loop due to the condition of (-current_node_pair.first)> lowerBound.

**Comment by WeiYan-Lynn** [comment]
> Thank you for your suggestion. But lowerbound will update at line 340, is that enough?
Obviously not, you can read the comments. And if there is no modification in your top, the lower limit will not be updated, resulting in an error exit from the loop due to the condition of (-current_node_pair.first)> lowerBound.

**Comment by zcdb** [comment]
Consider when lowerBound = 100 and dist = 200, your modification will update lowerBound to 200. At this time, come back and look at the judgment (-current_node_pair.first)> lowerBound. If -current_node_pair.first = 150, there is actually no need for subsequent calculations. Doesn't the judgment condition become broader? Wouldn't this add more invalid calculations? Such modifications will become unreasonable.

**Comment by WeiYan-Lynn** [comment]
Of course, you can consider a better modification method, but in this way, the previous results cannot update the top when the restriction condition is reached, and the subsequent results cannot be looped even if the condition for updating the top is met.

**Comment by zcdb** [comment]
In fact, when there is filtering, the search needs to expand the scope to obtain more possible values that meet the conditions, but at this time, modifying the lowerbound will introduce a lot of unnecessary calculations. A better strategy needs to be considered.

**Pull request closed without merging**
